apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokemon
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Learning-Factory/pokemon-manifests.git
    targetRevision: HEAD
    path: pokemon-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: pokemon
  # syncPolicy:
  #   automated:
  #     selfHeal: true