apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

secretGenerator:
- name: mysql-pass
  literals:
  - password=Control123
resources:
  - sealed-secret.yaml
  - mysql-deployment.yaml
  - pokemon-deployment.yaml
  - pokemon-ingress-nginx.yaml
